- name: ckecking files and directory ysing stat module
  hosts: web
  tasks:
    - name: check directory d2
      stat:
        path: /home/ec2-user/d2

      register: b

    - name: display output
      debug:
        var: b

    - name: create directory
      file:
        name: d2
        state: directory
      when: b.stat.exists == false
