- name: tagging in ansible
  hosts: web
  tasks:
    - name: install tree
      yum:
        name: tree
        state: present
      tags: tree
    - name: create user
      user:
        name: aws
        password: aws123
      tags: aws

    - name: copy files
      copy:
        src: /etc/passwd
        dest: /tmp
